// <auto-generated />
namespace Caixa.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajuste_Estabelecimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajuste_Estabelecimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201802010209585_Ajuste_Estabelecimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
