// <auto-generated />
namespace Caixa.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class regioes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(regioes));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201513403_regioes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
